/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CsrSponsorshipRouteImport } from './routes/csr-sponsorship'
import { Route as CookieSettingsRouteImport } from './routes/cookie-settings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsRssDotxmlRouteImport } from './routes/programs.rss[.]xml'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as PrivacyEmailsRouteImport } from './routes/privacy.emails'
import { Route as PortalFundraisersRouteImport } from './routes/portal.fundraisers'
import { Route as PortalCoordinatorsRouteImport } from './routes/portal.coordinators'
import { Route as NewsArchiveRouteImport } from './routes/news.archive'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GuidesMobilityAidGrantsRouteImport } from './routes/guides.mobility-aid-grants'
import { Route as GuidesFreeMedicalEquipmentRouteImport } from './routes/guides.free-medical-equipment'
import { Route as GuidesDonateSuppliesRouteImport } from './routes/guides.donate-supplies'
import { Route as FaqDonationsRouteImport } from './routes/faq.donations'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EmailPreferencesRouteImport } from './routes/email/preferences'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthDeleteAccountRouteImport } from './routes/auth.delete-account'
import { Route as AuthChangePasswordRouteImport } from './routes/auth.change-password'
import { Route as AuthCancelDeletionRouteImport } from './routes/auth.cancel-deletion'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicEmailPreferencesRouteImport } from './routes/api/public/email-preferences'
import { Route as ApiPublicCookieConsentLogRouteImport } from './routes/api/public/cookie-consent-log'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksPurgeDeletedAccountsRouteImport } from './routes/api/public/hooks/purge-deleted-accounts'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrSponsorshipRoute = CsrSponsorshipRouteImport.update({
  id: '/csr-sponsorship',
  path: '/csr-sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieSettingsRoute = CookieSettingsRouteImport.update({
  id: '/cookie-settings',
  path: '/cookie-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRssDotxmlRoute = ProgramsRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const PrivacyEmailsRoute = PrivacyEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => PrivacyRoute,
} as any)
const PortalFundraisersRoute = PortalFundraisersRouteImport.update({
  id: '/portal/fundraisers',
  path: '/portal/fundraisers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCoordinatorsRoute = PortalCoordinatorsRouteImport.update({
  id: '/portal/coordinators',
  path: '/portal/coordinators',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsArchiveRoute = NewsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const GuidesMobilityAidGrantsRoute = GuidesMobilityAidGrantsRouteImport.update({
  id: '/guides/mobility-aid-grants',
  path: '/guides/mobility-aid-grants',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFreeMedicalEquipmentRoute =
  GuidesFreeMedicalEquipmentRouteImport.update({
    id: '/guides/free-medical-equipment',
    path: '/guides/free-medical-equipment',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesDonateSuppliesRoute = GuidesDonateSuppliesRouteImport.update({
  id: '/guides/donate-supplies',
  path: '/guides/donate-supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqDonationsRoute = FaqDonationsRouteImport.update({
  id: '/faq/donations',
  path: '/faq/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPreferencesRoute = EmailPreferencesRouteImport.update({
  id: '/email/preferences',
  path: '/email/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeleteAccountRoute = AuthDeleteAccountRouteImport.update({
  id: '/auth/delete-account',
  path: '/auth/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCancelDeletionRoute = AuthCancelDeletionRouteImport.update({
  id: '/auth/cancel-deletion',
  path: '/auth/cancel-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailPreferencesRoute =
  ApiPublicEmailPreferencesRouteImport.update({
    id: '/api/public/email-preferences',
    path: '/api/public/email-preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCookieConsentLogRoute =
  ApiPublicCookieConsentLogRouteImport.update({
    id: '/api/public/cookie-consent-log',
    path: '/api/public/cookie-consent-log',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPurgeDeletedAccountsRoute =
  ApiPublicHooksPurgeDeletedAccountsRouteImport.update({
    id: '/api/public/hooks/purge-deleted-accounts',
    path: '/api/public/hooks/purge-deleted-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookie-settings': typeof CookieSettingsRoute
  '/csr-sponsorship': typeof CsrSponsorshipRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/request': typeof RequestRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/cancel-deletion': typeof AuthCancelDeletionRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/delete-account': typeof AuthDeleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/email/preferences': typeof EmailPreferencesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/faq/donations': typeof FaqDonationsRoute
  '/guides/donate-supplies': typeof GuidesDonateSuppliesRoute
  '/guides/free-medical-equipment': typeof GuidesFreeMedicalEquipmentRoute
  '/guides/mobility-aid-grants': typeof GuidesMobilityAidGrantsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/archive': typeof NewsArchiveRoute
  '/portal/coordinators': typeof PortalCoordinatorsRoute
  '/portal/fundraisers': typeof PortalFundraisersRoute
  '/privacy/emails': typeof PrivacyEmailsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/rss.xml': typeof ProgramsRssDotxmlRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/cookie-consent-log': typeof ApiPublicCookieConsentLogRoute
  '/api/public/email-preferences': typeof ApiPublicEmailPreferencesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookie-settings': typeof CookieSettingsRoute
  '/csr-sponsorship': typeof CsrSponsorshipRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/request': typeof RequestRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/cancel-deletion': typeof AuthCancelDeletionRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/delete-account': typeof AuthDeleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/email/preferences': typeof EmailPreferencesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/faq/donations': typeof FaqDonationsRoute
  '/guides/donate-supplies': typeof GuidesDonateSuppliesRoute
  '/guides/free-medical-equipment': typeof GuidesFreeMedicalEquipmentRoute
  '/guides/mobility-aid-grants': typeof GuidesMobilityAidGrantsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/archive': typeof NewsArchiveRoute
  '/portal/coordinators': typeof PortalCoordinatorsRoute
  '/portal/fundraisers': typeof PortalFundraisersRoute
  '/privacy/emails': typeof PrivacyEmailsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/rss.xml': typeof ProgramsRssDotxmlRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/cookie-consent-log': typeof ApiPublicCookieConsentLogRoute
  '/api/public/email-preferences': typeof ApiPublicEmailPreferencesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookie-settings': typeof CookieSettingsRoute
  '/csr-sponsorship': typeof CsrSponsorshipRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/request': typeof RequestRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/cancel-deletion': typeof AuthCancelDeletionRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/delete-account': typeof AuthDeleteAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/email/preferences': typeof EmailPreferencesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/faq/donations': typeof FaqDonationsRoute
  '/guides/donate-supplies': typeof GuidesDonateSuppliesRoute
  '/guides/free-medical-equipment': typeof GuidesFreeMedicalEquipmentRoute
  '/guides/mobility-aid-grants': typeof GuidesMobilityAidGrantsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/archive': typeof NewsArchiveRoute
  '/portal/coordinators': typeof PortalCoordinatorsRoute
  '/portal/fundraisers': typeof PortalFundraisersRoute
  '/privacy/emails': typeof PrivacyEmailsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/rss.xml': typeof ProgramsRssDotxmlRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/cookie-consent-log': typeof ApiPublicCookieConsentLogRoute
  '/api/public/email-preferences': typeof ApiPublicEmailPreferencesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/purge-deleted-accounts': typeof ApiPublicHooksPurgeDeletedAccountsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookie-settings'
    | '/csr-sponsorship'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/mcp'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/request'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/cancel-deletion'
    | '/auth/change-password'
    | '/auth/delete-account'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/dashboard/activity'
    | '/email/preferences'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/faq/donations'
    | '/guides/donate-supplies'
    | '/guides/free-medical-equipment'
    | '/guides/mobility-aid-grants'
    | '/news/$slug'
    | '/news/archive'
    | '/portal/coordinators'
    | '/portal/fundraisers'
    | '/privacy/emails'
    | '/programs/$slug'
    | '/programs/rss.xml'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/cookie-consent-log'
    | '/api/public/email-preferences'
    | '/lovable/email/suppression'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookie-settings'
    | '/csr-sponsorship'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/mcp'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/request'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/cancel-deletion'
    | '/auth/change-password'
    | '/auth/delete-account'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/dashboard/activity'
    | '/email/preferences'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/faq/donations'
    | '/guides/donate-supplies'
    | '/guides/free-medical-equipment'
    | '/guides/mobility-aid-grants'
    | '/news/$slug'
    | '/news/archive'
    | '/portal/coordinators'
    | '/portal/fundraisers'
    | '/privacy/emails'
    | '/programs/$slug'
    | '/programs/rss.xml'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/cookie-consent-log'
    | '/api/public/email-preferences'
    | '/lovable/email/suppression'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookie-settings'
    | '/csr-sponsorship'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/mcp'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/request'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/cancel-deletion'
    | '/auth/change-password'
    | '/auth/delete-account'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/dashboard/activity'
    | '/email/preferences'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/faq/donations'
    | '/guides/donate-supplies'
    | '/guides/free-medical-equipment'
    | '/guides/mobility-aid-grants'
    | '/news/$slug'
    | '/news/archive'
    | '/portal/coordinators'
    | '/portal/fundraisers'
    | '/privacy/emails'
    | '/programs/$slug'
    | '/programs/rss.xml'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/cookie-consent-log'
    | '/api/public/email-preferences'
    | '/lovable/email/suppression'
    | '/api/public/hooks/purge-deleted-accounts'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CookieSettingsRoute: typeof CookieSettingsRoute
  CsrSponsorshipRoute: typeof CsrSponsorshipRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyRoute: typeof PrivacyRouteWithChildren
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RequestRoute: typeof RequestRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCancelDeletionRoute: typeof AuthCancelDeletionRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthDeleteAccountRoute: typeof AuthDeleteAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  EmailPreferencesRoute: typeof EmailPreferencesRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FaqDonationsRoute: typeof FaqDonationsRoute
  GuidesDonateSuppliesRoute: typeof GuidesDonateSuppliesRoute
  GuidesFreeMedicalEquipmentRoute: typeof GuidesFreeMedicalEquipmentRoute
  GuidesMobilityAidGrantsRoute: typeof GuidesMobilityAidGrantsRoute
  PortalCoordinatorsRoute: typeof PortalCoordinatorsRoute
  PortalFundraisersRoute: typeof PortalFundraisersRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCookieConsentLogRoute: typeof ApiPublicCookieConsentLogRoute
  ApiPublicEmailPreferencesRoute: typeof ApiPublicEmailPreferencesRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksPurgeDeletedAccountsRoute: typeof ApiPublicHooksPurgeDeletedAccountsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr-sponsorship': {
      id: '/csr-sponsorship'
      path: '/csr-sponsorship'
      fullPath: '/csr-sponsorship'
      preLoaderRoute: typeof CsrSponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-settings': {
      id: '/cookie-settings'
      path: '/cookie-settings'
      fullPath: '/cookie-settings'
      preLoaderRoute: typeof CookieSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/rss.xml': {
      id: '/programs/rss.xml'
      path: '/rss.xml'
      fullPath: '/programs/rss.xml'
      preLoaderRoute: typeof ProgramsRssDotxmlRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/privacy/emails': {
      id: '/privacy/emails'
      path: '/emails'
      fullPath: '/privacy/emails'
      preLoaderRoute: typeof PrivacyEmailsRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/portal/fundraisers': {
      id: '/portal/fundraisers'
      path: '/portal/fundraisers'
      fullPath: '/portal/fundraisers'
      preLoaderRoute: typeof PortalFundraisersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/coordinators': {
      id: '/portal/coordinators'
      path: '/portal/coordinators'
      fullPath: '/portal/coordinators'
      preLoaderRoute: typeof PortalCoordinatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/archive': {
      id: '/news/archive'
      path: '/archive'
      fullPath: '/news/archive'
      preLoaderRoute: typeof NewsArchiveRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/guides/mobility-aid-grants': {
      id: '/guides/mobility-aid-grants'
      path: '/guides/mobility-aid-grants'
      fullPath: '/guides/mobility-aid-grants'
      preLoaderRoute: typeof GuidesMobilityAidGrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/free-medical-equipment': {
      id: '/guides/free-medical-equipment'
      path: '/guides/free-medical-equipment'
      fullPath: '/guides/free-medical-equipment'
      preLoaderRoute: typeof GuidesFreeMedicalEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/donate-supplies': {
      id: '/guides/donate-supplies'
      path: '/guides/donate-supplies'
      fullPath: '/guides/donate-supplies'
      preLoaderRoute: typeof GuidesDonateSuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/donations': {
      id: '/faq/donations'
      path: '/faq/donations'
      fullPath: '/faq/donations'
      preLoaderRoute: typeof FaqDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/preferences': {
      id: '/email/preferences'
      path: '/email/preferences'
      fullPath: '/email/preferences'
      preLoaderRoute: typeof EmailPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/delete-account': {
      id: '/auth/delete-account'
      path: '/auth/delete-account'
      fullPath: '/auth/delete-account'
      preLoaderRoute: typeof AuthDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cancel-deletion': {
      id: '/auth/cancel-deletion'
      path: '/auth/cancel-deletion'
      fullPath: '/auth/cancel-deletion'
      preLoaderRoute: typeof AuthCancelDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-preferences': {
      id: '/api/public/email-preferences'
      path: '/api/public/email-preferences'
      fullPath: '/api/public/email-preferences'
      preLoaderRoute: typeof ApiPublicEmailPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cookie-consent-log': {
      id: '/api/public/cookie-consent-log'
      path: '/api/public/cookie-consent-log'
      fullPath: '/api/public/cookie-consent-log'
      preLoaderRoute: typeof ApiPublicCookieConsentLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-deleted-accounts': {
      id: '/api/public/hooks/purge-deleted-accounts'
      path: '/api/public/hooks/purge-deleted-accounts'
      fullPath: '/api/public/hooks/purge-deleted-accounts'
      preLoaderRoute: typeof ApiPublicHooksPurgeDeletedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsArchiveRoute: typeof NewsArchiveRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsArchiveRoute: NewsArchiveRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PrivacyRouteChildren {
  PrivacyEmailsRoute: typeof PrivacyEmailsRoute
}

const PrivacyRouteChildren: PrivacyRouteChildren = {
  PrivacyEmailsRoute: PrivacyEmailsRoute,
}

const PrivacyRouteWithChildren =
  PrivacyRoute._addFileChildren(PrivacyRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsRssDotxmlRoute: typeof ProgramsRssDotxmlRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsRssDotxmlRoute: ProgramsRssDotxmlRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CookieSettingsRoute: CookieSettingsRoute,
  CsrSponsorshipRoute: CsrSponsorshipRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRouteWithChildren,
  PrivacyRoute: PrivacyRouteWithChildren,
  ProgramsRoute: ProgramsRouteWithChildren,
  RequestRoute: RequestRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCancelDeletionRoute: AuthCancelDeletionRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthDeleteAccountRoute: AuthDeleteAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  EmailPreferencesRoute: EmailPreferencesRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FaqDonationsRoute: FaqDonationsRoute,
  GuidesDonateSuppliesRoute: GuidesDonateSuppliesRoute,
  GuidesFreeMedicalEquipmentRoute: GuidesFreeMedicalEquipmentRoute,
  GuidesMobilityAidGrantsRoute: GuidesMobilityAidGrantsRoute,
  PortalCoordinatorsRoute: PortalCoordinatorsRoute,
  PortalFundraisersRoute: PortalFundraisersRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCookieConsentLogRoute: ApiPublicCookieConsentLogRoute,
  ApiPublicEmailPreferencesRoute: ApiPublicEmailPreferencesRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksPurgeDeletedAccountsRoute:
    ApiPublicHooksPurgeDeletedAccountsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
